version: "3.8"

services:
  api:
    container_name: api
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn start:prod
    depends_on:
      - postgres-db
      - redis
    environment:
      - NODE_ENV=production
    env_file: .env
    restart: unless-stopped
    ports:
      - "3000:3000"

  postgres-db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
volumes:
  db:
